<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Perfiles\Module'                        => __DIR__ . '/Module.php',
    'Perfiles\Controller\IndexController' => __DIR__ . '/src/Perfiles/Controller/IndexController.php',
);