<div class="portlet box blue">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-cogs"></i>Administraci&oacute;n de Tablas Param&eacute;tricaszxxxxxx
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse"></a>
            <a href="#portlet-config" data-toggle="modal" class="config"></a>
            <a href="javascript:;" class="reload"></a>
            <a href="javascript:;" class="remove"></a>
        </div>
    </div>
    <div class="portlet-body flip-scroll">
        <div class="row">
            <div class="col-md-3">

            </div>
            <div class="col-md-9">
                <div id="result">

                </div>
            </div>
        </div>
    </div>
</div>

