<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Administracion\Module'                        => __DIR__ . '/Module.php',
    'Administracion\Controller\IndexController' => __DIR__ . '/src/Administracion/Controller/IndexController.php',
    'Administracion\Controller\EquipoController' => __DIR__ . '/src/Administracion/Controller/EquipoController.php',
    'AdministracionTest\Framework\TestCase'        => __DIR__ . '/tests/Administracion/Framework/TestCase.php',
    'AdministracionTest\SampleTest'                => __DIR__ . '/tests/Administracion/SampleTest.php',
);