<div id="miArea">
<p class="text-center text-danger" style="font-weight: bold;">
    <?php echo $this->messages; ?>
</p>
<div class="login-panel panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Cambiar Clave</h3>
    </div>
    <div class="panel-body">

        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('auth-doctrine/default', array('controller' => 'registration', 'action' => 'cambiar-password')));
        $form->prepare();
        ?>
        <?php echo $this->form()->openTag($form); ?>
        <fieldset>
            <div class="form-group <?php if ($this->formElementErrors($form->get('usrName'))) echo "has-error"; else echo ""; ?>">
                <?php //echo $this->formRow($form->get('usrEmail')); ?>
                <span class="col-md-12"><?php echo $this->formLabel($form->get('usrName')); ?></span>
                <div class="col-md-12">
                    <?php echo $this->formInput($form->get('usrName')); ?>
                    <?php if ($this->formElementErrors($form->get('usrName'))) ?>
                    <span >
                        <?php echo $this->formElementErrors($form->get('usrName')) ?>
                    </span>
                </div>
            </div>

            <!--<div class="form-group <?php /*if ($this->formElementErrors($form->get('usrEmail'))) echo "has-error"; else echo ""; */?>">
                <?php /*//echo $this->formRow($form->get('usrEmail')); */?>
                <span class="col-md-12"><?php /*echo $this->formLabel($form->get('usrEmail')); */?></span>
                <div class="col-md-12">
                    <?php /*echo $this->formInput($form->get('usrEmail')); */?>
                    <?php /*if ($this->formElementErrors($form->get('usrEmail'))) */?>
                    <span >
                        <?php /*echo $this->formElementErrors($form->get('usrEmail')) */?>
                    </span>
                </div>
            </div>-->

            <div class="form-group <?php if ($this->formElementErrors($form->get('usrPasswordOld'))) echo "has-error"; else echo ""; ?>">
                <?php //echo $this->formRow($form->get('usrPassword')); ?>
                <span class="col-md-12"><?php echo $this->formLabel($form->get('usrPasswordOld')); ?></span>
                <div class="col-md-12">
                    <?php echo $this->formInput($form->get('usrPasswordOld')); ?>
                    <?php if ($this->formElementErrors($form->get('usrPasswordOld'))) ?>
                    <span >
                        <?php echo $this->formElementErrors($form->get('usrPasswordOld')) ?>
                    </span>
                </div>
            </div>

            <div class="form-group <?php if ($this->formElementErrors($form->get('usrPassword'))) echo "has-error"; else echo ""; ?>">
                <?php //echo $this->formRow($form->get('usrPassword')); ?>
                <span class="col-md-12"><?php echo $this->formLabel($form->get('usrPassword')); ?></span>
                <div class="col-md-12">
                    <?php echo $this->formInput($form->get('usrPassword')); ?>
                    <?php if ($this->formElementErrors($form->get('usrPassword'))) ?>
                    <span >
                        <?php echo $this->formElementErrors($form->get('usrPassword')) ?>
                    </span>
                </div>
            </div>
            <div class="form-group <?php if ($this->formElementErrors($form->get('usrPasswordConfirm'))) echo "has-error"; else echo ""; ?>">
                <?php //echo $this->formRow($form->get('usrPasswordConfirm')); ?>
                <span class="col-md-12"><?php echo $this->formLabel($form->get('usrPasswordConfirm')); ?></span>
                <div class="col-md-12">
                    <?php echo $this->formInput($form->get('usrPasswordConfirm')); ?>
                    <?php if ($this->formElementErrors($form->get('usrPasswordConfirm'))) ?>
                    <span >
                        <?php echo $this->formElementErrors($form->get('usrPasswordConfirm')) ?>
                    </span>
                </div>
            </div>

            <div class="form-actions fluid">
                <div class="col-md-offset-2 col-md-10">
                    <?php  echo $this->formRow($form->get('submit')); ?>
                    <a href="<?php echo $this->url('auth-doctrine/default', array('controller' => 'index', 'action' => 'logout'));?>">
                        <button class="btn btn-warning" type="button">Cancelar</button>
                    </a>
                </div>
            </div>
        </fieldset>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>
</div>


<!--<div align="right" style="padding: 0 10px 10px 0;">
    <a href="<?php /*echo $this->url('auth-doctrine/default', array('controller' => 'index', 'action' => 'login')); */?>">Inicio</a>
</div>-->
<div class="row">
    <div class="col-md-6 text-left">

    </div>
    <div class="col-md-6 text-right" >
        <a href="<?php echo $this->url('auth-doctrine/default', array('controller' => 'index', 'action' => 'logout')); ?>">Login</a>
    </div>
</div>
<br>
<br>
<br>

<?php
// *************** Eventos Jquery de validacion y envio de formulario por ajax
// ************************
// Plugins necesarios
/*
YsJQuery::usePlugin ( YsJQueryConstant::PLUGIN_JQVALIDATE );
YsJQuery::usePlugin ( YsJQueryConstant::PLUGIN_JQFORM );
YsJQuery::usePlugin ( YsJQueryConstant::PLUGIN_PNOTYFY );

echo YsJQuery::newInstance ()->execute (
    YsJQForm::ajaxForm ()
        ->in( '#registration' )
        ->_target ( '#miArea' )
        ->_dataType ( "json" )
        ->_beforeSubmit ( new YsJsFunction ( 'if(validar()){return true;}else{return false;}' ) )
        ->_success ( new YsJsFunction ( "successForm(response);", "response" ) ) );
*/
?>

<script type="text/javascript">
/*
    function validar(){
        var usrName = $('#usrName').val();
        alert(usrName);

        if(!confirm("Seguro de guardar4?")){return false;}

        return true;
    }


    function successForm(response){
        console.log(response);
        if (response.respuesta){
            jQuery.pnotify({'pnotify_text': 'SUCCESS','pnotify_type': 'notice'});
            //$("#content").load('/application/solicitudinsumo/index');
           // jQuery('#dialogIdFormularioSol').remove();
            //actualizarRegistrosSol();
        }else{
            jQuery.pnotify({'pnotify_text': response.mensaje.noObjectFound,'pnotify_type': 'error'});
            //window.location = '/auth-doctrine/registration/cambiar-password';
            $('#registration').submit;
            //form.submit;
        }

    }
    */
</script>